import { NextResponse } from "next/server";
import { db } from "@/lib/db";

const SECTORS = [
  // ═══════════════════════════════════════════
  // COMMERCE (5)
  // ═══════════════════════════════════════════
  {
    slug: "restauration-alimentaire",
    name: "Restauration & Alimentaire",
    description:
      "Restaurants, cafés, boulangeries, traiteurs et tous les métiers de la restauration et de la production alimentaire artisanale ou commerciale.",
    icon: "UtensilsCrossed",
    color: "amber",
    category: "commerce",
    tools: JSON.stringify([
      { name: "TouchBistro", category: "caisse", description: "Système de caisse spécialisé restauration avec gestion des tables et des commandes", slug: "touchbistro" },
      { name: "TheFork Manager", category: "réservation", description: "Gestion des réservations et avis clients en ligne", slug: "thefork-manager" },
      { name: "Melba", category: "gestion", description: "Logiciel de gestion pour la restauration : stocks, recettes, coûts", slug: "melba" },
      { name: "FoodMeUp", category: "recettes", description: "Logiciel de recettes et gestion des coûts alimentaires", slug: "foodmeup" },
      { name: "Uber Eats / Deliveroo Business", category: "livraison", description: "Plateforme de livraison de repas pour développer votre chiffre d'affaires", slug: "uber-eats-business" },
      { name: "Qonto", category: "banque", description: "Compte bancaire pro avec suivi des encaissements et gestion des notes de frais", slug: "qonto" },
      { name: "Shine", category: "banque", description: "Néo-banque adaptée aux indépendants et TPE du secteur restauration", slug: "shine" },
    ]),
    tips: JSON.stringify([
      "Commencez par un menu court et maîtrisé : qualité prime sur la quantité au lancement",
      "Mettez en place un système de réservation en ligne dès le premier jour pour optimiser le service",
      "Contrôlez vos coûts alimentaires dès le début : visez un food cost inférieur à 30%",
      "Investissez dans de belles photos de vos plats pour les réseaux sociaux et Google My Business",
      "Proposez une offre click & collect pour capter une clientèle locale sans frais de livraison",
    ]),
    regulations: JSON.stringify([
      "Déclaration préalable à la DDPP (Direction Départementale de la Protection des Populations) au moins 30 jours avant l'ouverture",
      "Formation HACCP obligatoire pour toute personne manipulant des denrées alimentaires",
      "Affichage obligatoire des allergènes sur le menu et en cuisine selon le règlement INCO 1169/2011",
      "Contrôle d'hygiène sanitaire par les services vétérinaires : préparez-vous à des inspections régulières",
    ]),
    active: true,
    order: 1,
  },
  {
    slug: "commerce-retail",
    name: "Commerce de Détail",
    description:
      "Boutiques, magasins spécialisés, franchises et points de vente physiques de proximité dans tous les secteurs : mode, déco, cadeaux, électronique, etc.",
    icon: "Store",
    color: "emerald",
    category: "commerce",
    tools: JSON.stringify([
      { name: "Lightspeed", category: "caisse", description: "Système de caisse et gestion de stock pour le commerce de détail", slug: "lightspeed" },
      { name: "Square", category: "paiement", description: "Terminal de paiement et solution POS complète avec gestion des ventes", slug: "square" },
      { name: "Loyoly", category: "fidélité", description: "Programme de fidélité et marketing client pour magasins indépendants", slug: "loyoly" },
      { name: "Cegid Retail", category: "erp", description: "Solution ERP complète pour la gestion de votre point de vente", slug: "cegid-retail" },
      { name: "Kiliba", category: "emailing", description: "Automatisation du marketing par email pour les commerçants", slug: "kiliba" },
      { name: "Trello", category: "organisation", description: "Gestion de vos tâches et projets : merchandising, promotions, events", slug: "trello" },
      { name: "Canva", category: "design", description: "Création de visuels promotionnels, affiches et contenu réseaux sociaux", slug: "canva" },
      { name: "Google My Business", category: "local", description: "Fiche Google pour apparaître dans les recherches locales et sur Maps", slug: "google-my-business" },
    ]),
    tips: JSON.stringify([
      "Investissez dans la vitrine : c'est votre première publicité, elle doit être attractive et changer régulièrement",
      "Mettez en place un système de caisse avec gestion de stock dès le jour 1 pour éviter les ruptures",
      "Créez un compte Google My Business complet avec photos pour attirer le trafic local",
      "Proposez le click & collect : 60% des consommateurs vérifient la disponibilité en ligne avant de se déplacer",
      "Organisez des événements en boutique (vernissages, ateliers) pour fidéliser et créer du bouche-à-oreille",
    ]),
    regulations: JSON.stringify([
      "Autorisation d'urbanisme (déclaration préalable ou permis de construire) selon la surface du local",
      "Déclaration d'activité au CFE (Centre de Formalités des Entreprises) avant l'ouverture",
      "Respect des normes ERP (Établissement Recevant du Public) pour l'accueil du public",
      "Affichage obligatoire des prix TTC en magasin et sur vitrine selon le code de la consommation",
    ]),
    active: true,
    order: 2,
  },
  {
    slug: "e-commerce",
    name: "E-Commerce",
    description:
      "Vente en ligne de produits physiques ou numériques via une boutique e-commerce. Du dropshipping au stock propre, du B2C au B2B marketplace.",
    icon: "ShoppingCart",
    color: "violet",
    category: "commerce",
    tools: JSON.stringify([
      { name: "Shopify", category: "plateforme", description: "Plateforme e-commerce complète avec thèmes et apps pour lancer votre boutique en ligne", slug: "shopify" },
      { name: "WooCommerce", category: "plateforme", description: "Solution e-commerce open source sur WordPress pour un contrôle total", slug: "woocommerce" },
      { name: "Sendinblue (Brevo)", category: "marketing", description: "Emailing, SMS et marketing automation pour votre boutique en ligne", slug: "sendinblue" },
      { name: "Pleeease", category: "logistique", description: "Solution de stockage, préparation et expédition de commandes e-commerce", slug: "pleeease" },
      { name: "Lengow", category: "distribution", description: "Diffusez vos produits sur les marketplaces (Amazon, Cdiscount, etc.)", slug: "lengow" },
      { name: "Prestashop", category: "plateforme", description: "CMS e-commerce open source avec de nombreuses fonctionnalités natives", slug: "prestashop" },
      { name: "Stripe", category: "paiement", description: "Solution de paiement en ligne sécurisée pour accepter cartes et virements", slug: "stripe" },
      { name: "Google Analytics 4", category: "analytics", description: "Suivez le trafic, les conversions et optimisez votre tunnel de vente", slug: "google-analytics-4" },
      { name: "Hotjar", category: "analyse", description: "Heatmaps et enregistrements de sessions pour comprendre le comportement visiteur", slug: "hotjar" },
    ]),
    tips: JSON.stringify([
      "Choisissez une niche bien définie plutôt que de tout vendre : la spécialisation attire et fidélise",
      "Optimisez vos fiches produits : photos de qualité, descriptions détaillées et avis clients visibles",
      "Mettez en place un tunnel d'abandon de panier : jusqu'à 70% des paniers sont abandonnés en moyenne",
      "Testez systématiquement vos process de livraison avec des commandes fictives avant le lancement",
      "Investissez dans le SEO de vos fiches produits pour capter du trafic qualifié sur le long terme",
    ]),
    regulations: JSON.stringify([
      "Conformité RGPD obligatoire : politique de confidentialité, mentions légales, gestion des cookies",
      "Droit de rétractation de 14 jours pour les ventes à distance (articles L221-18 à L221-28 du code de la consommation)",
      "Conditions générales de vente (CGV) accessibles et mentionnées avant toute commande",
      "Mentions légales complètes sur le site incluant les informations de l'éditeur et de l'hébergeur",
    ]),
    active: true,
    order: 3,
  },
  {
    slug: "commerce-ambulant",
    name: "Commerce Ambulant",
    description:
      "Food trucks, camions de vente, marchés, brocantes et tous les commerces itinérants. Vente directe de produits alimentaires ou non-alimentaires sur différents emplacements.",
    icon: "Truck",
    color: "orange",
    category: "commerce",
    tools: JSON.stringify([
      { name: "Square POS", category: "caisse", description: "Caisse mobile sur smartphone ou tablette pour le commerce ambulant", slug: "square-pos" },
      { name: "iZettle", category: "paiement", description: "Terminal de paiement mobile pour accepter les paiements partout", slug: "izettle" },
      { name: "FoodTruckr", category: "gestion", description: "Application de gestion pour food trucks : planning, emplacements, menu", slug: "foodtruckr" },
      { name: "Instagram", category: "réseaux", description: "Communiquez votre emplacement quotidien et attirez des clients grâce aux stories", slug: "instagram" },
      { name: "Google Maps", category: "local", description: "Indiquez votre position en temps réel pour les clients qui vous recherchent", slug: "google-maps" },
      { name: "Canva", category: "design", description: "Créez votre identité visuelle : menu, banderole, autocollant de food truck", slug: "canva" },
    ]),
    tips: JSON.stringify([
      "Constituez un réseau d'emplacements réguliers (marchés, zones d'activité, événements) pour fidéliser une clientèle",
      "Utilisez les réseaux sociaux, surtout Instagram Stories, pour communiquer votre position quotidienne",
      "Proposez une carte courte (5-7 items) mais exécutez-les parfaitement pour créer une réputation",
      "Investissez dans une signalétique claire et attractive : le visuel fait vendre même en ambulant",
      "Diversifiez vos points de vente : marchés le matin, zone d'activité le midi, événements le week-end",
    ]),
    regulations: JSON.stringify([
      "Carte de commerçant ambulant ou carte d'artisan ambulant obligatoire (délivrée par la CCI/CMA)",
      "Autorisation d'occupation du domaine public nécessaire pour chaque emplacement municipal",
      "Licence de vente de boissons si vous vendez de l'alcool (licence III ou IV)",
      "Assurance responsabilité civile professionnelle obligatoire pour couvrir les risques liés à l'activité itinérante",
    ]),
    active: true,
    order: 4,
  },
  {
    slug: "epicerie-specialisee",
    name: "Épicerie Spécialisée",
    description:
      "Épiceries fines, bio, locales, du monde, cavistes, chocolatiers et tous les commerces de détail alimentaire spécialisé proposant des produits de qualité.",
    icon: "Wine",
    color: "rose",
    category: "commerce",
    tools: JSON.stringify([
      { name: "Odoo POS", category: "caisse", description: "Caisse enregistreuse connectée à un système de gestion de stock complet", slug: "odoo-pos" },
      { name: "Clock", category: "caisse", description: "Solution de caisse simple et abordable adaptée aux petites épiceries", slug: "clock" },
      { name: "Loyoly", category: "fidélité", description: "Programme de fidélité digital pour créer une relation durable avec vos clients", slug: "loyoly" },
      { name: "Google My Business", category: "local", description: "Soyez visible dans les recherches locales et collectez des avis clients", slug: "google-my-business-epicerie" },
      { name: "Trello", category: "gestion", description: "Gérez vos approvisionnements, promotions et événements dégustation", slug: "trello-epicerie" },
      { name: "Canva", category: "design", description: "Créez des étiquettes produits, affiches de promotions et visuels réseaux sociaux", slug: "canva-epicerie" },
    ]),
    tips: JSON.stringify([
      "Misez sur le storytelling de vos produits : l'origine, le producteur, le terroir font la différence",
      "Organisez des dégustations régulières pour faire découvrir de nouveaux produits et créer du lien",
      "Créez des coffrets cadeaux et lots thématiques (fêtes, saisonniers) pour augmenter le panier moyen",
      "Développez une offre de click & collect pour les clients pressés qui veulent passer récupérer leur commande",
      "Collaborez avec les producteurs locaux : circuits courts et exclusivités attirent la clientèle",
    ]),
    regulations: JSON.stringify([
      "Déclaration à la DDPP et respect de la chaîne du froid pour les produits périssables",
      "Formation HACCP obligatoire pour la manipulation de denrées alimentaires",
      "Règles d'étiquetage spécifiques pour les produits bio (logo AB européen obligatoire)",
      "Déclaration de conformité sanitaire des locaux auprès des services vétérinaires",
    ]),
    active: true,
    order: 5,
  },

  // ═══════════════════════════════════════════
  // SERVICES (8)
  // ═══════════════════════════════════════════
  {
    slug: "conseil-b2b",
    name: "Conseil B2B",
    description:
      "Cabinets de conseil, consulting, expertise métier et accompagnement stratégique pour les entreprises. Stratégie, organisation, transformation digitale, finances et management.",
    icon: "Briefcase",
    color: "blue",
    category: "services",
    tools: JSON.stringify([
      { name: "Notion", category: "productivité", description: "Espace de travail collaboratif pour gérer missions, livrables et knowledge base", slug: "notion" },
      { name: "Slack", category: "communication", description: "Communication d'équipe et échanges avec vos clients en temps réel", slug: "slack" },
      { name: "Pipedrive", category: "crm", description: "CRM pour suivre votre pipeline commercial et gérer les relations clients B2B", slug: "pipedrive" },
      { name: "Miro", category: "collaboration", description: "Tableau blanc collaboratif pour les ateliers, brainstormings et workshops clients", slug: "miro" },
      { name: "Pitch", category: "présentation", description: "Création de présentations professionnelles et decks de conseil", slug: "pitch" },
      { name: "Calendly", category: "rdv", description: "Planification automatique de vos rendez-vous et sessions de conseil", slug: "calendly" },
      { name: "Jotform", category: "formulaires", description: "Création de formulaires d'intake client et questionnaires de diagnostic", slug: "jotform" },
      { name: "Xero", category: "comptabilité", description: "Gestion comptable simplifiée pour les consultants et freelances B2B", slug: "xero" },
    ]),
    tips: JSON.stringify([
      "Définissez votre positionnement clairement : un cabinet de conseil qui veut tout faire ne convainc personne",
      "Publiquez régulièrement du contenu à forte valeur ajoutée (white papers, études de cas) pour asseoir votre expertise",
      "Fixez vos tarifs à la valeur apportée, pas au temps passé : c'est le modèle le plus rentable en conseil",
      "Constituez un réseau de partenaires complémentaires pour répondre à des appels d'offres plus larges",
      "Mettez en place un CRM dès le départ pour suivre prospects, clients et opportunités de manière structurée",
    ]),
    regulations: JSON.stringify([
      "Aucune réglementation spécifique pour le conseil général, mais des obligations selon la spécialité (financière, juridique)",
      "Assurance responsabilité civile professionnelle fortement recommandée couvrant les erreurs de conseil",
      "Respect du secret professionnel et de la confidentialité des données clients (RGPD/NDA)",
      "Facturation conformément aux usages du secteur avec conditions de paiement et pénalités de retard",
    ]),
    active: true,
    order: 6,
  },
  {
    slug: "formation-education",
    name: "Formation & Éducation",
    description:
      "Organismes de formation, auto-entrepreneurs formateurs, écoles privées et coaching éducatif. Formation professionnelle, continue, certifiante ou en ligne.",
    icon: "BookOpen",
    color: "teal",
    category: "services",
    tools: JSON.stringify([
      { name: "Teachable", category: "e-learning", description: "Plateforme de création et vente de cours en ligne avec suivi des apprenants", slug: "teachable" },
      { name: "Thinkific", category: "e-learning", description: "Hébergement de cours en ligne avec outils marketing intégrés", slug: "thinkific" },
      { name: "Zoom", category: "visioconférence", description: "Visioconférence fiable pour les sessions de formation en direct", slug: "zoom" },
      { name: "Typeform", category: "quiz", description: "Création de quiz, évaluations et formulaires d'inscription interactifs", slug: "typeform" },
      { name: "Notion", category: "contenu", description: "Organisation de vos contenus pédagogiques et plans de formation", slug: "notion-formation" },
      { name: "Calendly", category: "planning", description: "Planification automatique des sessions de formation individuelles", slug: "calendly-formation" },
      { name: "Loom", category: "vidéo", description: "Enregistrement de vidéos de formation asynchrones avec suivi des visionnages", slug: "loom" },
    ]),
    tips: JSON.stringify([
      "Obtenez la certification Qualiopi dès que possible : c'est indispensable pour facturer des organismes financeurs",
      "Structurez vos formations en modules courts et progressifs pour maximiser l'engagement des apprenants",
      "Investissez dans la qualité de vos supports pédagogiques : c'est votre principale publicité",
      "Recueillez systématiquement les retours et témoignages de vos stagiaires pour nourrir votre marketing",
      "Diversifiez vos formats : présentiel, visio, e-learning et blended learning pour toucher plus de publics",
    ]),
    regulations: JSON.stringify([
      "Certification Qualiopi obligatoire pour accéder aux financements OPCO, Pôle Emploi et Région",
      "Déclaration d'activité de formateur auprès de la DREETS (ex-Direccte) avant le début de la première formation",
      "Convention de formation obligatoire pour toute formation de plus de 2 heures financée par un tiers",
      "Respect des règles de la formation professionnelle continue (bilan pédagogique, attestation de fin de formation)",
    ]),
    active: true,
    order: 7,
  },
  {
    slug: "coaching-developpement",
    name: "Coaching & Développement Personnel",
    description:
      "Coaching professionnel, coaching de vie, développement personnel, mentoring et accompagnement individuel pour entrepreneurs, cadres et particuliers.",
    icon: "Heart",
    color: "rose",
    category: "services",
    tools: JSON.stringify([
      { name: "Calendly", category: "rdv", description: "Planification de sessions de coaching avec rappels automatiques", slug: "calendly-coaching" },
      { name: "Zoom", category: "visio", description: "Sessions de coaching en visioconférence avec qualité audio optimale", slug: "zoom-coaching" },
      { name: "Notion", category: "suivi", description: "Suivi des objectifs et progrès de vos coachés avec tableaux de bord personnalisés", slug: "notion-coaching" },
      { name: "Stripe", category: "paiement", description: "Paiement sécurisé pour les pack de sessions et abonnements de coaching", slug: "stripe-coaching" },
      { name: "Canva", category: "supports", description: "Création de supports visuels : wheel of life, goal setters, trackers", slug: "canva-coaching" },
      { name: "Google Forms", category: "questionnaires", description: "Questionnaires d'intake et bilans de compétences en ligne", slug: "google-forms-coaching" },
    ]),
    tips: JSON.stringify([
      "Spécialisez-vous : un coach généraliste a plus de mal à se démarquer qu'un coach expert d'un domaine",
      "Offrez un premier rendez-vous découverte (20-30 min) pour convertir les prospects : c'est votre meilleur outil de vente",
      "Demandez systématiquement des témoignages et références après chaque cycle de coaching réussi",
      "Fixez des objectifs mesurables dès la première session : c'est ce qui prouve votre valeur",
      "Développez une offre groupée (pack de 5 ou 10 séances) pour sécuriser votre revenu et l'engagement du client",
    ]),
    regulations: JSON.stringify([
      "Aucune réglementation d'accès à la profession de coach (contrairement au psychologue ou thérapeute)",
      "Le titre de coach n'est pas protégé : des certifications (ICF, EMCC) renforcent la crédibilité",
      "Obligation de respecter le cadre déontologique de la fédération de coaching choisie (ICF recommandée)",
      "Assurance responsabilité civile professionnelle recommandée pour couvrir les risques liés à l'accompagnement",
    ]),
    active: true,
    order: 8,
  },
  {
    slug: "evenementiel",
    name: "Événementiel",
    description:
      "Organisation d'événements professionnels et privés : séminaires, team building, mariages, concerts, salons, conférences et conventions. De la conception à la logistique.",
    icon: "PartyPopper",
    color: "violet",
    category: "services",
    tools: JSON.stringify([
      { name: "Eventbrite", category: "billetterie", description: "Plateforme de billetterie et d'inscription pour vos événements", slug: "eventbrite" },
      { name: "Weezevent", category: "billetterie", description: "Solution française de billetterie avec gestion des participants et paiement", slug: "weezevent" },
      { name: "Trello", category: "projet", description: "Gestion de projet pour suivre toutes les étapes de l'organisation événementielle", slug: "trello-evenement" },
      { name: "Canva", category: "design", description: "Création de supports visuels : affiches, programmes, badges, signalétique", slug: "canva-evenement" },
      { name: "Asana", category: "planning", description: "Planification détaillée des tâches, deadlines et responsables", slug: "asana" },
      { name: "Notion", category: "documentation", description: "Documentation des process événementiels et retrospectives", slug: "notion-evenement" },
      { name: "Google Workspace", category: "collaboration", description: "Suite collaborative pour les dossiers de production et les plannings partagés", slug: "google-workspace-evenement" },
      { name: "Slack", category: "communication", description: "Communication temps réel avec l'équipe de production le jour J", slug: "slack-evenement" },
    ]),
    tips: JSON.stringify([
      "Créez un portfolio visuel de vos événements passés : c'est votre meilleur argument de vente",
      "Anticipez toujours 20% de budget supplémentaire pour les imprévus (météo, retards, urgences)",
      "Développez un réseau de prestataires fiables (traiteurs, techniciens, loueurs) pour garantir la qualité",
      "Le jour J, déléguez : vous ne pouvez pas tout gérer seul, assignez des zones de responsabilité claires",
      "Recueillez des retours participants après chaque événement pour améliorer et capitaliser",
    ]),
    regulations: JSON.stringify([
      "Licence d'entrepreneur de spectacles vivants obligatoire si vous organisez des événements payants avec spectacle",
      "Déclaration en préfecture pour les manifestations sur la voie publique (3 mois minimum avant)",
      "Assurance responsabilité civile professionnelle spécifique événementielle obligatoire",
      "Plan de prévention des risques et sécurité incendie selon le nombre de participants et le type de lieu",
    ]),
    active: true,
    order: 9,
  },
  {
    slug: "securite-gardiennage",
    name: "Sécurité & Gardiennage",
    description:
      "Sociétés de gardiennage, surveillance, sécurité incendie, télésurveillance, contrôle d'accès et services de sécurité pour entreprises et particuliers.",
    icon: "Shield",
    color: "blue",
    category: "services",
    tools: JSON.stringify([
      { name: "Guard Tour Systems", category: "gestion", description: "Système de contrôle des rondes et suivi des agents de sécurité", slug: "guard-tour-systems" },
      { name: "Vigie", category: "télésurveillance", description: "Plateforme de télésurveillance connectée pour le monitoring à distance", slug: "vigie" },
      { name: "SIR Presto", category: "planning", description: "Logiciel de gestion du personnel et planification des rotations d'agents", slug: "sir-presto" },
      { name: "Canva", category: "supports", description: "Création de rapports de sécurité, badges et documents de procédure", slug: "canva-securite" },
      { name: "Google Forms", category: "rapports", description: "Formulaires numériques pour les rapports d'intervention et comptes-rendus", slug: "google-forms-securite" },
      { name: "Slack", category: "communication", description: "Communication sécurisée entre agents de sécurité et coordination des équipes", slug: "slack-securite" },
    ]),
    tips: JSON.stringify([
      "L'agrément CNAPS (Conseil National des Activités Privées de Sécurité) est obligatoire avant toute activité",
      "Investissez dans la formation continue de vos agents : la qualité du personnel est votre meilleur argument",
      "Mettez en place des process documentés et standardisés pour garantir la qualité et la traçabilité",
      "Proposez des audits de sécurité gratuits comme outil de prospection et de démonstration de votre expertise",
      "Diversifiez vos services : télésurveillance, installation d'alarmes, conseil en sécurité pour augmenter le CA",
    ]),
    regulations: JSON.stringify([
      "Agrément préfectoral obligatoire auprès de la CNAPS pour toute activité de sécurité privée",
      "Carte professionnelle d'agent de sécurité obligatoire pour chaque agent employé",
      "Formation initiale obligatoire de 140 heures pour les agents de sécurité",
      "Déclaration trimestrielle à la CNAPS de l'ensemble des salariés exerçant des activités de sécurité",
    ]),
    active: true,
    order: 10,
  },
  {
    slug: "proprete-entretien",
    name: "Propreté & Entretien",
    description:
      "Entreprises de nettoyage, entretien de locaux, services de ménage professionnel, nettoyage industriel et façadiers. Bureaux, copropriétés, chantiers et espaces publics.",
    icon: "Sparkles",
    color: "teal",
    category: "services",
    tools: JSON.stringify([
      { name: "Clean Smarts", category: "gestion", description: "Logiciel de gestion des équipes de nettoyage et suivi des interventions", slug: "clean-smarts" },
      { name: "Jobber", category: "planning", description: "Planification des interventions, facturation et suivi client", slug: "jobber" },
      { name: "Swept", category: "opérations", description: "Application mobile pour les équipes de terrain avec contrôles qualité", slug: "swept" },
      { name: "Qonto", category: "banque", description: "Gestion bancaire adaptée avec suivi des encaissements et décaissements", slug: "qonto-proprete" },
      { name: "Google Forms", category: "contrôle", description: "Checklists de contrôle qualité numériques pour les interventions", slug: "google-forms-proprete" },
      { name: "Canva", category: "design", description: "Devis, factures et supports de communication professionnelle", slug: "canva-proprete" },
    ]),
    tips: JSON.stringify([
      "Fidélisez vos clients avec des contrats d'entretien annuels plutôt que des interventions ponctuelles",
      "Recrutez des personnes fiables et formez-les aux process : la qualité humaine fait la différence",
      "Équipez vos équipes de produits professionnels de qualité : cela améliore l'efficacité et réduit le temps de nettoyage",
      "Proposez des audits gratuits comme outil de prospection pour identifier les besoins et démontrer votre expertise",
      "Misez sur l'éco-responsabilité : produits d'entretien écologiques et démarche RSE pour vous différencier",
    ]),
    regulations: JSON.stringify([
      "Carte BTP obligatoire pour les intervenants sur les chantiers de construction",
      "Attestation de formation à la sécurité pour les travaux en hauteur et les espaces confinés",
      "Respect des normes de sécurité et d'hygiène pour les produits et procédés de nettoyage",
      "Obligation de fourniture d'EPI (équipements de protection individuelle) adaptés aux tâches",
    ]),
    active: true,
    order: 11,
  },
  {
    slug: "traduction-redaction",
    name: "Traduction & Rédaction",
    description:
      "Services de traduction, rédaction web, copywriting, content marketing et création de contenu. Français, anglais et langues étrangères pour entreprises et particuliers.",
    icon: "Languages",
    color: "amber",
    category: "services",
    tools: JSON.stringify([
      { name: "Trados Studio", category: "traduction", description: "Logiciel de traduction assistée par ordinateur (TAO) pour les projets volumineux", slug: "trados-studio" },
      { name: "Memsource", category: "tao", description: "Plateforme cloud de traduction et gestion de mémoires de traduction", slug: "memsource" },
      { name: "Grammarly", category: "correction", description: "Assistant d'écriture et correction grammaticale pour un contenu sans fautes", slug: "grammarly" },
      { name: "Notion", category: "organisation", description: "Gestion de vos projets de rédaction, calendrier éditorial et briefs clients", slug: "notion-redaction" },
      { name: "Canva", category: "présentation", description: "Mise en page de contenus, infographies et supports visuels pour vos textes", slug: "canva-redaction" },
      { name: "Trello", category: "pipeline", description: "Suivi des commandes de traduction et rédaction à travers les étapes de production", slug: "trello-redaction" },
      { name: "Calendly", category: "rdv", description: "Prise de rendez-vous pour les briefs créatifs avec vos clients", slug: "calendly-redaction" },
      { name: "Stripe", category: "paiement", description: "Paiement en ligne sécurisé pour vos prestations de services", slug: "stripe-redaction" },
    ]),
    tips: JSON.stringify([
      "Spécialisez-vous dans 1-2 domaines (juridique, médical, marketing, technique) pour augmenter vos tarifs",
      "Constituez un portfolio de vos meilleurs textes et traductions pour convaincre de nouveaux clients",
      "Proposez des tests de traduction gratuits (300-500 mots) comme outil de prospection efficace",
      "Diversifiez vos canaux d'acquisition : plateformes freelance, LinkedIn, agences de traduction et contact direct",
      "Automatisez votre facturation et relances avec un logiciel pour gagner du temps sur l'administratif",
    ]),
    regulations: JSON.stringify([
      "Aucune réglementation d'accès à la profession de traducteur ou rédacteur freelance",
      "Certification ISO 17100 pour les sociétés de traduction (norme qualité pour les services de traduction)",
      "Respect du droit d'auteur et des licences d'utilisation des images et contenus de vos rédactions",
      "Obligation de facturation et déclaration des revenus comme travailleur indépendant",
    ]),
    active: true,
    order: 12,
  },
  {
    slug: "services-domicile",
    name: "Services à Domicile",
    description:
      "Aide à domicile, ménage, garde d'enfants, assistance aux personnes âgées, pet-sitting et tous les services rendus au domicile des particuliers.",
    icon: "Home",
    color: "emerald",
    category: "services",
    tools: JSON.stringify([
      { name: "AlloVoisins", category: "plateforme", description: "Plateforme de mise en relation pour les services de proximité entre particuliers", slug: "allovoisins" },
      { name: "Ryvalto", category: "gestion", description: "Logiciel de facturation et suivi client pour les services à domicile", slug: "ryvalto" },
      { name: "Planity", category: "rdv", description: "Prise de rendez-vous en ligne pour vos interventions à domicile", slug: "planity" },
      { name: "Google Calendar", category: "planning", description: "Organisation de votre planning d'interventions avec rappels SMS", slug: "google-calendar-domicile" },
      { name: "WhatsApp Business", category: "communication", description: "Communication directe avec vos clients pour confirmations et suivi", slug: "whatsapp-business" },
      { name: "Qonto", category: "banque", description: "Gestion bancaire simplifiée pour les auto-entrepreneurs du service à domicile", slug: "qonto-domicile" },
    ]),
    tips: JSON.stringify([
      "La confiance est clé : demandez des avis à chaque intervention et affichez-les fièrement",
      "Optimisez vos tournées géographiquement pour maximiser le nombre d'interventions par jour",
      "Proposez des packs d'abonnement (mensuel, trimestriel) pour sécuriser un revenu régulier",
      "Investissez dans un uniforme ou une tenue professionnelle pour inspirer confiance dès le premier contact",
      "Utilisez le chèque emploi-service universel (CESU) ou Presta-services pour faciliter le paiement",
    ]),
    regulations: JSON.stringify([
      "Déclaration d'activité auprès de l'URSSAF et immatriculation au registre du commerce pour les entreprises",
      "Obligation de certification qualité pour accéder à l'avantage fiscal de réduction d'impôt (50%) pour les particuliers",
      "Formation obligatoire pour les aides à domicile (TP AIIDE de 140h minimum) si emploi direct",
      "Contrat de travail et bulletin de paie obligatoires pour tout employé de maison déclaré",
    ]),
    active: true,
    order: 13,
  },

  // ═══════════════════════════════════════════
  // ARTISANAT (7)
  // ═══════════════════════════════════════════
  {
    slug: "btp-construction",
    name: "BTP & Construction",
    description:
      "Entreprises du bâtiment et travaux publics : gros œuvre, maçonnerie, couverture, plomberie, électricité, carrelage et tous les corps d'état du bâtiment.",
    icon: "HardHat",
    color: "amber",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "Batappli", category: "chantier", description: "Application de gestion de chantier pour suivre l'avancement des travaux", slug: "batappli" },
      { name: "Tolteck", category: "devis", description: "Logiciel de devis et facturation spécifique au BTP avec bibliothèque d'ouvrages", slug: "tolteck" },
      { name: "PlanRadar", category: "suivi", description: "Application mobile de suivi de chantier avec documentation photo et rapports", slug: "planradar" },
      { name: "Obat", category: "erp", description: "ERP complet pour les artisans du BTP : devis, factures, achats, stocks", slug: "obat" },
      { name: "Artisan Connect", category: "rdv", description: "Plateforme de mise en relation artisans-clients et prise de rendez-vous", slug: "artisan-connect" },
      { name: "Google Workspace", category: "communication", description: "Communication avec clients, architectes et partenaires de chantier", slug: "google-workspace-btp" },
      { name: "Qonto", category: "banque", description: "Gestion bancaire adaptée aux artisans avec suivi des encaissements chantiers", slug: "qonto-btp" },
    ]),
    tips: JSON.stringify([
      "Obtenez vos qualifications et certifications (RGE, Qualibat) : c'est indispensable pour les chantiers aidés et les assurances",
      "Prenez le temps de bien chiffrer vos devis : un chantier mal estimé peut mettre en péril votre entreprise",
      "Photographiez chaque étape du chantier pour votre traçabilité et en cas de litige",
      "Répondez aux devis dans les 24h : la réactivité est le critère n°1 de choix d'un artisan",
      "Investissez dans vos outils de production : du matériel de qualité améliore votre productivité et votre image",
    ]),
    regulations: JSON.stringify([
      "Inscription à la Chambre des Métiers (CMA) et registre des métiers obligatoire",
      "Assurance décennale obligatoire pour les constructions neuves et gros œuvre",
      "Carte BTP obligatoire pour tout intervenant sur un chantier de construction",
      "Respect de la norme RT2012/RE2020 pour toute construction neuve ou rénovation importante",
    ]),
    active: true,
    order: 14,
  },
  {
    slug: "artisanat-batiment",
    name: "Artisanat du Bâtiment",
    description:
      "Artisans spécialisés du bâtiment : peinture, menuiserie, serrurerie, métallerie, plâtrerie, isolation, carrelage et finitions intérieures et extérieures.",
    icon: "Hammer",
    color: "orange",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "Tolteck", category: "devis", description: "Création de devis et factures professionnels spécifiques aux artisans du bâtiment", slug: "tolteck-artisanat" },
      { name: "HappyCo", category: "devis", description: "Logiciel de devis et facturation simple et abordable pour les artisans", slug: "happyco" },
      { name: "Obat", category: "gestion", description: "Gestion de vos chantiers, achats de matériaux et facturation fournisseurs", slug: "obat-artisanat" },
      { name: "Google My Business", category: "local", description: "Référencement local pour être trouvé par les particuliers dans votre zone", slug: "google-my-business-artisanat" },
      { name: "Instagram", category: "portfolio", description: "Montrez vos réalisations en photos pour attirer de nouveaux clients", slug: "instagram-artisanat" },
      { name: "Canva", category: "design", description: "Créez des avant/après professionnels pour vos supports commerciaux", slug: "canva-artisanat" },
    ]),
    tips: JSON.stringify([
      "Les avant/après de vos chantiers sont votre meilleure publicité : postez-les systématiquement",
      "Demandez systématiquement des avis Google et Facebook à vos clients satisfaits",
      "Prix au m² ou au forfait clairement affiché sur votre site pour rassurer les prospects",
      "Gardez un stock de matériel minimal pour être réactif sans immobiliser trop de trésorerie",
      "Répondez aux demandes de devis sur Houzz, Travaux.com et autres plateformes pour augmenter votre visibilité",
    ]),
    regulations: JSON.stringify([
      "Inscription au répertoire des métiers (CMA) obligatoire pour exercer en tant qu'artisan",
      "Garantie décennale obligatoire même pour les travaux de second œuvre (finitions, carrelage)",
      "Délégation de paiement obligatoire pour les travaux > 3000€ dans les copropriétés (loi SRU)",
      "Respect des normes acoustiques et thermiques en vigueur pour les rénovations",
    ]),
    active: true,
    order: 15,
  },
  {
    slug: "coiffure-barbier",
    name: "Coiffure & Barbier",
    description:
      "Salons de coiffure, barbiers, coiffeurs à domicile et centres de beauté capillaire. Coupe, coloration, soins et tendances pour homme, femme et enfant.",
    icon: "Scissors",
    color: "rose",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "Planity", category: "rdv", description: "Solution de prise de rendez-vous en ligne n°1 pour les salons de coiffure", slug: "planity-coiffure" },
      { name: "Treatwell", category: "rdv", description: "Plateforme de réservation pour salons de beauté et coiffure", slug: "treatwell" },
      { name: "Phenix", category: "caisse", description: "Logiciel de caisse et gestion de clientèle pour les salons de coiffure", slug: "phenix" },
      { name: "Shine", category: "banque", description: "Néo-banque adaptée aux artisans-coiffeurs avec gestion des encaissements", slug: "shine-coiffure" },
      { name: "Instagram", category: "réseaux", description: "Vitrine de vos créations et tendance : indispensable pour un salon moderne", slug: "instagram-coiffure" },
      { name: "Canva", category: "design", description: "Création de visuels promotionnels, cartes de fidélité et communication salon", slug: "canva-coiffure" },
    ]),
    tips: JSON.stringify([
      "Instagram est votre vitrine : postez au minimum 3-4 fois par semaine des avant/après de vos coupes",
      "Mettez en place un système de prise de rendez-vous en ligne pour réduire les appels téléphoniques",
      "Proposez des cartes de fidélité digitales : un client fidèle dépense 3 à 4 fois plus qu'un client nouveau",
      "Créez une ambiance unique dans votre salon : musique, décoration, café = expérience client différenciante",
      "Formez-vous régulièrement aux nouvelles techniques et tendances pour rester compétitif",
    ]),
    regulations: JSON.stringify([
      "Diplôme de coiffeur obligatoire (CAP coiffure ou équivalent) pour exercer",
      "Déclaration d'activité auprès de la Chambre des Métiers (CMA) obligatoire",
      "Respect des normes d'hygiène et de sécurité sanitaire des locaux (aération, produits chimiques)",
      "Assurance responsabilité civile professionnelle obligatoire pour couvrir les accidents éventuels",
    ]),
    active: true,
    order: 16,
  },
  {
    slug: "photographie-video",
    name: "Photographie & Vidéo",
    description:
      "Photographes et vidéastes professionnels : mariage, portrait, produit, immobilier, événementiel, corporate et production audiovisuelle. Studio et tournage.",
    icon: "Camera",
    color: "violet",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "Lightroom", category: "retouche", description: "Logiciel de retouche photo professionnel pour le traitement de vos images", slug: "lightroom" },
      { name: "Capture One", category: "retouche", description: "Logiciel de traitement RAW de référence pour les photographes professionnels", slug: "capture-one" },
      { name: "Premiere Pro", category: "montage", description: "Logiciel de montage vidéo professionnel pour vos productions", slug: "premiere-pro" },
      { name: "Pixieset", category: "galerie", description: "Galeries photos en ligne professionnelles pour la livraison à vos clients", slug: "pixieset" },
      { name: "Tave", category: "studio", description: "Gestion complète de studio : CRM, contrats, factures et workflow", slug: "tave" },
      { name: "Canva", category: "design", description: "Création de moodboards, présentations et supports commerciaux", slug: "canva-photo" },
      { name: "Calendly", category: "rdv", description: "Prise de rendez-vous pour les séances photo et consultations clients", slug: "calendly-photo" },
    ]),
    tips: JSON.stringify([
      "Constituez un portfolio en ligne de haute qualité sur un site professionnel dédié",
      "Spécialisez-vous dans 1-2 domaines pour vous positionner comme expert et justifier des tarifs premium",
      "Le bouche-à-oreille est votre meilleur outil marketing : offrez des tirages pour les ambassadeurs",
      "Sauvegardez systématiquement vos photos sur 3 supports différents (local, cloud, externe)",
      "Facturez un acompte de 30 à 50% à la réservation pour sécuriser vos engagements",
    ]),
    regulations: JSON.stringify([
      "Pas de diplôme obligatoire pour exercer comme photographe ou vidéaste",
      "Droit à l'image : consentement obligatoire pour toute personne photographiée ou filmée",
      "Propriété intellectuelle : le photographe conserve les droits sur ses images sauf cession expresse",
      "Assurance responsabilité civile professionnelle indispensable pour couvrir les dommages matériels",
    ]),
    active: true,
    order: 17,
  },
  {
    slug: "serigraphie-impression",
    name: "Sérigraphie & Impression",
    description:
      "Ateliers de sérigraphie, impression textile, impression numérique, grand format, signalétique et fabrication d'objets personnalisés. T-shirts, casquettes, posters et supports imprimés.",
    icon: "Printer",
    color: "blue",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "CorelDRAW", category: "design", description: "Logiciel de vectorisation et prépresse pour la sérigraphie et l'impression", slug: "coreldraw" },
      { name: "Illustrator", category: "design", description: "Création de visuels vectoriels pour fichiers d'impression haute qualité", slug: "illustrator" },
      { name: "Tolteck", category: "devis", description: "Gestion de devis et commandes pour vos commandes d'impression personnalisée", slug: "tolteck-serigraphie" },
      { name: "Shopify", category: "e-commerce", description: "Boutique en ligne pour vendre vos créations personnalisées", slug: "shopify-serigraphie" },
      { name: "Instagram", category: "réseaux", description: "Montrez vos processus de création et réalisations finies", slug: "instagram-serigraphie" },
      { name: "Notion", category: "gestion", description: "Gestion de vos commandes, suivi de production et base de clients", slug: "notion-serigraphie" },
    ]),
    tips: JSON.stringify([
      "Investissez dans du matériel de qualité dès le départ : le rendu final en dépend directement",
      "Proposez des packs personnalisés (tenues d'équipe, événements, merch) pour augmenter le panier moyen",
      "Les tutos vidéo de votre processus créatif sur les réseaux sociaux génèrent énormément d'engagement",
      "Créez un catalogue en ligne de vos modèles et options pour faciliter les commandes",
      "Développez des partenariats avec des entreprises pour des commandes régulières (uniformes, goodies)",
    ]),
    regulations: JSON.stringify([
      "Inscription à la Chambre des Métiers (CMA) obligatoire pour les activités artisanales",
      "Respect des normes environnementales pour le traitement des produits chimiques (solvants, encres)",
      "Déclaration d'installation ICPE si utilisation de produits chimiques classés",
      "Obligation d'étiquetage des compositions textiles selon le règlement européen REACH",
    ]),
    active: true,
    order: 18,
  },
  {
    slug: "artisanat-d-art",
    name: "Artisanat d'Art",
    description:
      "Artisans d'art, créateurs, bijoutiers, céramistes, verriers, menuisiers d'art et restaurateurs d'œuvres. Création de pièces uniques et restaurations pour particuliers et institutions.",
    icon: "Gem",
    color: "emerald",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "Shopify", category: "e-commerce", description: "Boutique en ligne pour vendre vos créations artisanales", slug: "shopify-artisanat-art" },
      { name: "Instagram", category: "réseaux", description: "Plateforme essentielle pour les artisans d'art : partage du processus créatif", slug: "instagram-artisanat-art" },
      { name: "Squarespace", category: "portfolio", description: "Site portfolio élégant pour présenter vos créations et votre univers", slug: "squarespace" },
      { name: "Canva", category: "design", description: "Création d'étiquettes, cartes de visite et supports pour foires et marchés", slug: "canva-artisanat-art" },
      { name: "Google Workspace", category: "gestion", description: "Gestion des commandes personnalisées et communication avec les clients", slug: "google-workspace-artisanat-art" },
      { name: "Stripe", category: "paiement", description: "Paiement en ligne sécurisé pour vos ventes et commandes sur mesure", slug: "stripe-artisanat-art" },
    ]),
    tips: JSON.stringify([
      "Participez activement aux marchés d'artisans, salons et foires pour développer votre notoriété locale",
      "Racontez l'histoire de chaque pièce : le savoir-faire, les matériaux, le temps de création sont vos arguments de vente",
      "Proposez des stages ou ateliers découverte pour diversifier vos revenus et créer une communauté",
      "Photographiez vos créations dans un éclairage professionnel : l'image fait vendre les pièces artisanales",
      "Obtenez le label Entreprise du Patrimoine Vivant (EPV) si vous avez plus de 10 ans d'existence",
    ]),
    regulations: JSON.stringify([
      "Inscription à la Chambre des Métiers (CMA) obligatoire pour les artisans d'art",
      "Titre de Maître Artisan accessible après 10 ans d'expérience et présentation d'un dossier devant un jury",
      "Assurance spécifique pour la couverture des œuvres et pièces de valeur en atelier et en transport",
      "Attestation de conformité CE pour les objets créés si destinés au public (bijoux, céramique alimentaire)",
    ]),
    active: true,
    order: 19,
  },
  {
    slug: "automobile-moto",
    name: "Automobile & Moto",
    description:
      "Garages automobiles, concessions, carrosseries, centres de contrôle technique, préparateurs et ateliers de réparation moto. Entretien, mécanique, carrosserie et customisation.",
    icon: "Wrench",
    color: "orange",
    category: "artisanat",
    tools: JSON.stringify([
      { name: "MecaProg", category: "garage", description: "Logiciel de gestion de garage : ordres de réparation, facturation, stock pièces", slug: "mecaprog" },
      { name: "Autobiz", category: "gestion", description: "Logiciel de gestion complet pour garages et carrosseries automobiles", slug: "autobiz" },
      { name: "GargeOnline", category: "planning", description: "Planification des rendez-vous clients et gestion du planning atelier", slug: "garage-online" },
      { name: "Google My Business", category: "local", description: "Soyez visible localement et collectez des avis clients sur votre garage", slug: "google-my-business-auto" },
      { name: "Qonto", category: "banque", description: "Gestion bancaire adaptée aux garages avec suivi des encaissements", slug: "qonto-auto" },
      { name: "Canva", category: "communication", description: "Création de promotions, flyers et contenu réseaux sociaux pour le garage", slug: "canva-auto" },
    ]),
    tips: JSON.stringify([
      "La transparence sur les prix et les réparations est votre meilleur argument face aux franchises",
      "Proposez un service de rappel d'entretien programmé pour fidéliser votre clientèle sur le long terme",
      "Investissez dans un équipement de diagnostic moderne : les véhicules connectés représentent 70% du parc",
      "Communiquez sur vos certifications (réparateur agréé, constructeur) et vos garanties",
      "Mettez en place un service de vidange express et petites réparations sans rendez-vous pour capter le trafic immédiat",
    ]),
    regulations: JSON.stringify([
      "Immatriculation au registre des métiers et qualification professionnelle obligatoire",
      "Certification automobile obligatoire depuis 2022 pour les garages de réparation et entretien",
      "Gestion des déchets d'activités économiques (DAE) obligatoire : huiles, pneus, batteries, liquides",
      "Conformité aux installations classées pour le stockage de produits dangereux (carburants, solvants)",
    ]),
    active: true,
    order: 20,
  },

  // ═══════════════════════════════════════════
  // SANTE & BIEN-ETRE (5)
  // ═══════════════════════════════════════════
  {
    slug: "sante-medical",
    name: "Santé & Médical",
    description:
      "Cabinets médicaux, cabinets infirmiers, pharmacies, laboratoires d'analyses, centres de soins et tout professionnel de santé réglementé exerçant en libéral ou en cabinet.",
    icon: "Stethoscope",
    color: "rose",
    category: "sante-bien-etre",
    tools: JSON.stringify([
      { name: "Doctolib", category: "rdv", description: "Plateforme de prise de rendez-vous et gestion de patientèle pour les professionnels de santé", slug: "doctolib" },
      { name: "Maiia", category: "rdv", description: "Alternative française à Doctolib pour la prise de rendez-vous médicale", slug: "maiia" },
      { name: "Hellocare", category: "téléconsultation", description: "Plateforme de téléconsultation pour les consultations à distance", slug: "hellocare" },
      { name: "Weda", category: "cabinet", description: "Logiciel de gestion de cabinet médical avec dossier patient et facturation", slug: "weda" },
      { name: "Mediboard", category: "dmp", description: "Gestion des dossiers médicaux et partage de documents de santé", slug: "mediboard" },
      { name: "Google My Business", category: "local", description: "Fiche locale pour votre cabinet avec horaires et avis patients", slug: "google-my-business-medical" },
      { name: "Trello", category: "organisation", description: "Organisation de la gestion administrative du cabinet", slug: "trello-medical" },
    ]),
    tips: JSON.stringify([
      "Mettez en place une prise de rendez-vous en ligne pour réduire les appels téléphoniques de 40%",
      "Communiquez vos horaires et disponibilités clairement en ligne pour réduire les no-shows",
      "Développez une offre de téléconsultation pour élargir votre zone de patientèle",
      "Maintenez votre fiche Google à jour : photos du cabinet, horaires, spécialités et avis patients",
      "Optimisez votre accueil téléphonique : c'est le premier contact du patient avec votre cabinet",
    ]),
    regulations: JSON.stringify([
      "Inscription obligatoire à l'Ordre professionnel compétent (médecins, infirmiers, pharmaciens, etc.)",
      "Conformité HDS (Hébergement de Données de Santé) obligatoire pour les données patients",
      "Secret médical et confidentialité des données de santé encadrés par le code de la santé publique",
      "Convention avec l'Assurance Maladie pour l'exercice en secteur conventionné (tarifs réglementés)",
    ]),
    active: true,
    order: 21,
  },
  {
    slug: "bien-etre-coaching",
    name: "Bien-Être & Coaching",
    description:
      "Praticiens de bien-être, sophrologues, naturopathes, hypnothérapeutes, réflexologues et professionnels du développement personnel holistique.",
    icon: "Leaf",
    color: "emerald",
    category: "sante-bien-etre",
    tools: JSON.stringify([
      { name: "Calendly", category: "rdv", description: "Planification de consultations avec rappels automatiques par email/SMS", slug: "calendly-bienetre" },
      { name: "Zoom", category: "visio", description: "Consultations en visioconférence pour les patients à distance", slug: "zoom-bienetre" },
      { name: "Stripe", category: "paiement", description: "Paiement en ligne sécurisé pour les consultations et pack de séances", slug: "stripe-bienetre" },
      { name: "Notion", category: "suivi", description: "Suivi personnalisé des parcours patients avec recommandations et bilans", slug: "notion-bienetre" },
      { name: "Instagram", category: "réseaux", description: "Partage de conseils bien-être, relaxation et développement personnel", slug: "instagram-bienetre" },
      { name: "Canva", category: "supports", description: "Création de supports de relaxation, guides et contenus éducatifs", slug: "canva-bienetre" },
      { name: "Mailchimp", category: "newsletters", description: "Newsletters de bien-être, conseils saisonniers et fidélisation patients", slug: "mailchimp-bienetre" },
    ]),
    tips: JSON.stringify([
      "Positionnez-vous clairement : le bien-être n'est pas la médecine, communiquez votre cadre d'intervention",
      "Offrez une première consultation découverte de 20 minutes pour rassurer et convertir les prospects",
      "Développez des contenus éducatifs réguliers (vidéos, articles) pour asseoir votre expertise et attirer des patients",
      "Créez des offres pack (5, 10 séances) avec un tarif dégressif pour encourager l'engagement dans la durée",
      "Recueillez des témoignages pour rassurer les nouveaux patients et construire votre réputation",
    ]),
    regulations: JSON.stringify([
      "Le titre de naturopathe, sophrologue ou hypnothérapeute n'est pas réglementé en France",
      "Les praticiens de bien-être ne peuvent en aucun cas poser de diagnostic médical ni prescrire de traitement",
      "Formation certifiante auprès d'un organisme reconnu recommandée pour la crédibilité professionnelle",
      "Assurance responsabilité civile professionnelle indispensable pour couvrir les risques liés à l'accompagnement",
    ]),
    active: true,
    order: 22,
  },
  {
    slug: "sport-fitness",
    name: "Sport & Fitness",
    description:
      "Salles de sport, coachs sportifs personnels, studios de yoga, Pilates, crossfit et toutes les activités sportives en présentiel ou en ligne.",
    icon: "Dumbbell",
    color: "amber",
    category: "sante-bien-etre",
    tools: JSON.stringify([
      { name: "Mindbody", category: "planning", description: "Logiciel de gestion de salle : planning, réservations, abonnements et paiements", slug: "mindbody" },
      { name: "HelloAsso", category: "paiement", description: "Solution de paiement et d'inscription sans frais pour les associations sportives", slug: "helloasso" },
      { name: "Glofox", category: "gestion", description: "Application de gestion de studio fitness avec suivi des membres et retentions", slug: "glofox" },
      { name: "YouTube", category: "contenu", description: "Diffusion de vos séances et tutoriels pour attirer et fidéliser votre audience", slug: "youtube-sport" },
      { name: "Instagram", category: "réseaux", description: "Plateforme incontournable pour les coachs sportifs : programmes, transformations, motivation", slug: "instagram-sport" },
      { name: "Strava", category: "communauté", description: "Réseau social sportif pour suivre vos clients et créer une communauté active", slug: "strava" },
      { name: "Canva", category: "design", description: "Création de programmes d'entraînement visuels, posters de motivation et contenus", slug: "canva-sport" },
    ]),
    tips: JSON.stringify([
      "Offrez un essai gratuit d'une semaine pour convertir les prospects : le taux de conversion est de 30 à 50%",
      "Développez des programmes en ligne (vidéos, PDF) pour créer un revenu passif complémentaire",
      "La communauté est votre atout : créez des groupes WhatsApp ou Facebook pour fidéliser vos membres",
      "Postez du contenu quotidiennement (shorts, reels) sur Instagram et TikTok pour gagner en visibilité",
      "Organisez des défis collectifs (30 jours, 12 semaines) pour stimuler l'engagement et les résultats",
    ]),
    regulations: JSON.stringify([
      "Diplôme d'État (BPJEPS, DEJEPS) obligatoire pour encadrer des activités sportives contre rémunération",
      "Déclaration d'activité auprès de la Direction Départementale de la Cohésion Sociale (DDCS)",
      "Certification Qualiopi obligatoire si vous proposez des formations sportives financées",
      "Assurance responsabilité civile professionnelle spécifique sport obligatoire pour les coachs et salles",
    ]),
    active: true,
    order: 23,
  },
  {
    slug: "beaute-cosmetique",
    name: "Beauté & Cosmétique",
    description:
      "Instituts de beauté, esthéticiennes, maquilleuses pro, onychologues et centres de soins esthétiques. Soins du visage, du corps, maquillage, épilation et onglerie.",
    icon: "Sparkles",
    color: "violet",
    category: "sante-bien-etre",
    tools: JSON.stringify([
      { name: "Planity", category: "rdv", description: "Prise de rendez-vous en ligne pour instituts de beauté et esthéticiennes", slug: "planity-beaute" },
      { name: "Treatwell", category: "rdv", description: "Plateforme de réservation leader pour les salons de beauté", slug: "treatwell-beaute" },
      { name: "Phenix", category: "caisse", description: "Logiciel de caisse avec gestion de clientèle et programmes de fidélité", slug: "phenix-beaute" },
      { name: "Instagram", category: "réseaux", description: "Vitrine indispensable pour les instituts : résultats de soins, ambiance, promotions", slug: "instagram-beaute" },
      { name: "Canva", category: "design", description: "Création de supports promotionnels, cartes de fidélité et contenu visuel", slug: "canva-beaute" },
      { name: "Loyoly", category: "fidélité", description: "Programme de fidélité digital pour fidéliser vos clientes", slug: "loyoly-beaute" },
    ]),
    tips: JSON.stringify([
      "Les transformations visuelles (avant/après) sont votre publicité la plus efficace : publiez-les avec l'accord de vos clientes",
      "Proposez des forfaits soins réguliers (4-6 séances) avec tarif avantageux pour fidéliser sur l'année",
      "L'expérience client compte autant que le soin : ambiance, musique, tisane = différenciation",
      "Vendez des produits complémentaires à domicile pour augmenter le panier moyen et fidéliser",
      "Formez-vous régulièrement aux nouvelles techniques et technologies (LED, radiofréquence, etc.)",
    ]),
    regulations: JSON.stringify([
      "Diplôme de CAP Esthétique Cosmétique Parfumerie ou BP Esthétique obligatoire pour exercer",
      "Déclaration d'activité auprès de la Chambre des Métiers (CMA) et inscription au registre des métiers",
      "Respect des normes sanitaires et d'hygiène des locaux et du matériel de l'institut",
      "Formation et certification obligatoires pour l'utilisation de certains appareils (laser, injections, etc.)",
    ]),
    active: true,
    order: 24,
  },
  {
    slug: "paramedical",
    name: "Paramédical",
    description:
      "Professionnels paramédicaux libéraux : kinésithérapeutes, ostéopathes, podologues, orthophonistes, psychomotriciens, diététiciens et ergothérapeutes.",
    icon: "Activity",
    color: "teal",
    category: "sante-bien-etre",
    tools: JSON.stringify([
      { name: "Doctolib", category: "rdv", description: "Prise de rendez-vous en ligne pour les professionnels paramédicaux conventionnés", slug: "doctolib-paramedical" },
      { name: "Maiia", category: "rdv", description: "Plateforme française de prise de rendez-vous pour le paramédical", slug: "maiia-paramedical" },
      { name: "Kinedoc", category: "cabinet", description: "Logiciel de gestion de cabinet pour les professions paramédicales", slug: "kinedoc" },
      { name: "Olympe", category: "cabinet", description: "Solution de gestion complète pour les cabinets de kinésithérapie", slug: "olympe" },
      { name: "Google My Business", category: "local", description: "Fiche locale avec avis patients pour renforcer votre visibilité de quartier", slug: "google-my-business-paramedical" },
      { name: "Notion", category: "suivi", description: "Suivi des parcours de soins et bilans patients", slug: "notion-paramedical" },
    ]),
    tips: JSON.stringify([
      "Acceptez le paiement par carte et virement pour faciliter la vie de vos patients (TPE mobile)",
      "Rappelez vos patients la veille de leur rendez-vous pour réduire les no-shows (10-15% en moyenne)",
      "Communiquez vos spécialités et domaines d'expertise sur votre fiche Google et votre site",
      "Proposez des créneaux de téléconsultation pour les suivis ne nécessitant pas de manipulation",
      "Misez sur le relationnel : le paramédical est avant tout une profession de confiance et de contact humain",
    ]),
    regulations: JSON.stringify([
      "Diplôme d'État obligatoire pour toutes les professions paramédicales réglementées",
      "Inscription obligatoire à l'Ordre professionnel compétent (kinésithérapeutes, pédicures, etc.)",
      "Convention avec l'Assurance Maladie pour le tiers payant et le remboursement des actes",
      "Secret professionnel et confidentialité des données de santé des patients (conformité RGPD et HDS)",
    ]),
    active: true,
    order: 25,
  },

  // ═══════════════════════════════════════════
  // TECH & NUMERIQUE (5)
  // ═══════════════════════════════════════════
  {
    slug: "informatique-tech",
    name: "Informatique & Tech",
    description:
      "Prestataires informatiques, dépannage, maintenance, installation réseaux, cybersécurité, infogérance et assistance technique pour entreprises et particuliers.",
    icon: "Monitor",
    color: "blue",
    category: "tech-numerique",
    tools: JSON.stringify([
      { name: "ITGlue", category: "documentation", description: "Documentation IT et base de connaissances pour les prestataires informatiques", slug: "itglue" },
      { name: "Atera", category: "rmm", description: "Plateforme RMM/PSP pour la surveillance et maintenance à distance des systèmes", slug: "atera" },
      { name: "ConnectWise", category: "psa", description: "Suite de gestion de services IT : tickets, facturation, reporting", slug: "connectwise" },
      { name: "NinjaOne", category: "rmm", description: "Outil de surveillance et gestion à distance des endpoints et serveurs", slug: "ninjaone" },
      { name: "TeamViewer", category: "assistance", description: "Assistance à distance fiable pour le support technique de vos clients", slug: "teamviewer" },
      { name: "Slack", category: "communication", description: "Communication avec vos clients pour les alertes et incidents techniques", slug: "slack-informatique" },
      { name: "Qonto", category: "banque", description: "Gestion bancaire adaptée avec suivi des abonnements et facturation récurrente", slug: "qonto-informatique" },
      { name: "Stripe", category: "paiement", description: "Paiement récurrent pour les contrats de maintenance et infogérance", slug: "stripe-informatique" },
    ]),
    tips: JSON.stringify([
      "Proposez des contrats de maintenance préventive pour sécuriser un revenu mensuel récurrent",
      "Développez une offre de cybersécurité : la demande explose et les marges sont excellentes",
      "Répondez aux urgences en moins de 30 minutes : la réactivité est le critère n°1 pour les clients",
      "Standardisez vos interventions avec des checklists pour garantir la qualité et la traçabilité",
      "Formez-vous en continu : les technologies évoluent vite et vos clients ont besoin d'un expert à jour",
    ]),
    regulations: JSON.stringify([
      "Pas de réglementation spécifique pour le dépannage informatique grand public",
      "Certification CNIL recommandée pour les prestataires traitant des données personnelles de leurs clients",
      "Respect du RGPD et mise en conformité des systèmes informatiques de vos clients",
      "Assurance responsabilité civile professionnelle indispensable pour les dommages informatiques potentiels",
    ]),
    active: true,
    order: 26,
  },
  {
    slug: "marketing-communication",
    name: "Marketing & Communication",
    description:
      "Agences de communication, consultants marketing, social media managers, copywriters et experts en publicité digitale. Stratégie, création et diffusion de campagnes.",
    icon: "Megaphone",
    color: "rose",
    category: "tech-numerique",
    tools: JSON.stringify([
      { name: "Meta Business Suite", category: "réseaux", description: "Gestion de vos pages Facebook et Instagram : publications, ads, insights", slug: "meta-business-suite" },
      { name: "Google Ads", category: "publicité", description: "Gestion de campagnes publicitaires sur Google Search, Display et YouTube", slug: "google-ads" },
      { name: "Mailchimp", category: "emailing", description: "Automatisation de campagnes d'emailing et newsletters", slug: "mailchimp-marketing" },
      { name: "Canva Pro", category: "design", description: "Création de visuels marketing professionnels pour tous les supports", slug: "canva-marketing" },
      { name: "Hootsuite", category: "social", description: "Planification et gestion centralisée de vos publications réseaux sociaux", slug: "hootsuite" },
      { name: "Notion", category: "gestion", description: "Gestion de projets marketing, calendrier éditorial et suivi des campagnes", slug: "notion-marketing" },
      { name: "SEMrush", category: "seo", description: "Analyse SEO, recherche de mots-clés et veille concurrentielle", slug: "semrush" },
      { name: "Figma", category: "design", description: "Maquettes et prototypage de landing pages et supports de communication", slug: "figma" },
      { name: "Buffer", category: "social", description: "Planification intelligente de publications sur les réseaux sociaux", slug: "buffer" },
    ]),
    tips: JSON.stringify([
      "Misez sur les études de cas : montrez des résultats concrets (ROI, trafic, leads) pour convaincre vos prospects",
      "Spécialisez-vous sur 2-3 canaux maximum plutôt que de promettre d'être partout",
      "Proposez un audit gratuit comme porte d'entrée pour démontrer votre expertise et générer des leads",
      "Mesurez et reportez systématiquement : les chiffres sont la meilleure preuve de votre valeur",
      "Restez formé : le marketing digital évolue chaque mois, l'obsolescence est votre plus grand risque",
    ]),
    regulations: JSON.stringify([
      "Respect du code de la publicité et des mentions légales obligatoires sur tous les supports",
      "Conformité RGPD pour le traitement des données de prospection et des cookies de tracking",
      "Déclaration de la base de données de prospects à la CNIL si traitement automatisé",
      "Transparence sur les relations commerciales et publicité influencer (loi Influence du 9 juin 2023)",
    ]),
    active: true,
    order: 27,
  },
  {
    slug: "design-graphisme",
    name: "Design & Graphisme",
    description:
      "Designers graphiques, directeurs artistiques, illustrateurs et agences de design. Identité visuelle, UI/UX, print, packaging et création de contenus visuels.",
    icon: "Palette",
    color: "violet",
    category: "tech-numerique",
    tools: JSON.stringify([
      { name: "Figma", category: "design", description: "Outil de design collaboratif n°1 : UI, UX, maquettes et prototypage", slug: "figma-design" },
      { name: "Adobe Creative Suite", category: "creation", description: "Suite complète : Illustrator, Photoshop, InDesign, After Effects", slug: "adobe-creative-suite" },
      { name: "Canva Pro", category: "rapid-design", description: "Création rapide de visuels pour les livrables de moindre complexité", slug: "canva-design" },
      { name: "Dribbble", category: "portfolio", description: "Plateforme de portfolio pour designers : montrez vos travaux et trouvez des clients", slug: "dribbble" },
      { name: "Behance", category: "portfolio", description: "Portfolio créatif par Adobe pour exposer vos projets et réalisations", slug: "behance" },
      { name: "Notion", category: "briefs", description: "Gestion des briefs clients, suivis de projets et archivage des livrables", slug: "notion-design" },
      { name: "Calendly", category: "rdv", description: "Planification des appels découverte et présentations de concepts", slug: "calendly-design" },
      { name: "Stripe", category: "paiement", description: "Facturation et paiement sécurisé pour vos prestations de design", slug: "stripe-design" },
    ]),
    tips: JSON.stringify([
      "Votre portfolio est votre CV : mettez-le à jour régulièrement avec vos projets les plus récents",
      "Proposez 3 concepts différents au client plutôt qu'un seul : le choix valorise votre travail",
      "Fixez des limites claires sur les allers-retours (2-3 max) pour éviter les projets sans fin",
      "Spécialisez-vous dans un domaine (branding, UI/UX, illustration) pour vous différencier",
      "Documentez votre process de création : les clients adorent voir comment vous travaillez",
    ]),
    regulations: JSON.stringify([
      "Aucune réglementation d'accès à la profession de designer graphique",
      "Droit d'auteur sur les créations : le designer conserve les droits sauf cession expresse contractuelle",
      "Respect des droits de propriété intellectuelle sur les polices, images et ressources utilisées",
      "Contrat de cession de droits nécessaire pour la revente et l'utilisation commerciale des créations",
    ]),
    active: true,
    order: 28,
  },
  {
    slug: "immobilier",
    name: "Immobilier",
    description:
      "Agences immobilières, agents commerciaux, syndics de copropriété, conseillers en gestion de patrimoine et investisseurs immobiliers. Transaction, location et gestion.",
    icon: "Building2",
    color: "teal",
    category: "tech-numerique",
    tools: JSON.stringify([
      { name: "SeLoger Pro", category: "annonces", description: "Diffusion d'annonces immobilières sur le portail n°1 en France", slug: "seloger-pro" },
      { name: "Immo-Neuf", category: "annonces", description: "Plateforme de diffusion d'annonces pour le neuf et la promotion immobilière", slug: "immo-neuf" },
      { name: "Proprioo", category: "gestion", description: "Logiciel de gestion locative et syndic de copropriété", slug: "proprioo" },
      { name: "RealIT", category: "gestion", description: "CRM et gestion de transaction immobilière pour les agents", slug: "realit" },
      { name: "Canva", category: "supports", description: "Création de brochures immobilières, cartes de visite et annonces visuelles", slug: "canva-immobilier" },
      { name: "Google My Business", category: "local", description: "Fiche locale de votre agence avec avis clients et visuels des biens", slug: "google-my-business-immobilier" },
      { name: "Matterport", category: "visite", description: "Visites virtuelles 3D pour améliorer l'expérience d'achat en ligne", slug: "matterport" },
    ]),
    tips: JSON.stringify([
      "Investissez dans des photos professionnelles de vos biens : c'est le critère n°1 de décision d'un acheteur",
      "Les visites virtuelles (Matterport) augmentent le taux de demande de visite réelle de 95%",
      "Répondez aux demandes dans l'heure : le marché immobilier récompense les agents réactifs",
      "Développez votre réseau de partenaires : notaires, banquiers, diagnostiqueurs = pipeline de prospects",
      "Créez du contenu local (quartier, écoles, transports) : ça positionne votre agence comme expert local",
    ]),
    regulations: JSON.stringify([
      "Carte T (transaction immobilière) obligatoire pour exercer la profession d'agent immobilier",
      "Diplôme ou expérience professionnelle validée pour l'inscription à la carte professionnelle",
      "Garantie financière de transaction obligatoire (minimum 30 000€) pour les agences",
      "Respect de la loi Hoguet encadrant les activités d'intermédiation et de gestion immobilière",
    ]),
    active: true,
    order: 29,
  },
  {
    slug: "transport-logistique",
    name: "Transport & Logistique",
    description:
      "Entreprises de transport, coursiers, déménageurs, transitaires, entreposage et logistique. Transport de marchandises, de personnes et services de livraison du dernier kilomètre.",
    icon: "Truck",
    color: "amber",
    category: "tech-numerique",
    tools: JSON.stringify([
      { name: "Samsara", category: "flotte", description: "GPS et gestion de flotte : suivi véhicules, consommation, sécurité", slug: "samsara" },
      { name: "Onfleet", category: "livraison", description: "Logiciel de gestion de la livraison du dernier kilomètre", slug: "onfleet" },
      { name: "ShipBob", category: "logistique", description: "Solution de stockage et expédition e-commerce externalisée", slug: "shipbob" },
      { name: "Trello", category: "planning", description: "Organisation des tournées et gestion des plannings de livraison", slug: "trello-transport" },
      { name: "Google Maps", category: "navigation", description: "Optimisation des itinéraires et suivi en temps réel des livraisons", slug: "google-maps-transport" },
      { name: "Qonto", category: "banque", description: "Gestion bancaire avec suivi des encaissements et frais de carburant", slug: "qonto-transport" },
      { name: "Notion", category: "documentation", description: "Documentation des procédures, consignes de sécurité et protocoles clients", slug: "notion-transport" },
      { name: "WhatsApp Business", category: "communication", description: "Communication avec les clients et chauffeurs pour les mises à jour de livraison", slug: "whatsapp-business-transport" },
    ]),
    tips: JSON.stringify([
      "Optimisez vos tournées avec un logiciel de routage : les économies de carburant peuvent atteindre 20%",
      "Proposez un suivi en temps réel des livraisons : c'est devenu un standard attendu par les clients",
      "Investissez dans des véhicules propres pour anticiper les ZFE (Zones à Faibles Émissions) en expansion",
      "Diversifiez vos contrats : B2C + B2B + marketplace pour lisser votre activité sur l'année",
      "Automatisez la facturation : avec des centaines de livraisons mensuelles, l'automatisation est indispensable",
    ]),
    regulations: JSON.stringify([
      "Licence de transport commun de marchandises obligatoire pour les véhicules > 3,5 tonnes",
      "Attestation de capacité professionnelle obligatoire pour le transport de marchandises",
      "Conformité aux réglementations sociales européennes (temps de conduite et de repos)",
      "Assurance marchandises transportées et responsabilité civile professionnelle obligatoires",
    ]),
    active: true,
    order: 30,
  },
];

export async function POST() {
  try {
    const existingCount = await db.activitySector.count();

    if (existingCount > 0) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Des secteurs d'activité existent déjà. Supprimez-les d'abord si vous souhaitez les réinitialiser.",
          existingCount,
        },
        { status: 409 }
      );
    }

    const result = await db.$transaction(
      SECTORS.map((sector) =>
        db.activitySector.create({
          data: sector,
        })
      )
    );

    return NextResponse.json(
      {
        success: true,
        message: `${result.length} secteurs d'activité créés avec succès`,
        sectorsCreated: result.length,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Activity sector seed error:", error);
    return NextResponse.json(
      { error: "Erreur lors de la création des secteurs d'activité" },
      { status: 500 }
    );
  }
}
